---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: ":github: Trigger E2E Tests (no wait)"
    plugins:
      - elastic/vault-github-token#v0.1.0:
      - elastic/gh-cli#${BUILDKITE_COMMIT}:
          version: "2.62.0"
          workflow-file: "e2e-test.yml"
          workflow-ref: "main"
          workflow-inputs:
            enable-debug: "false"
            environment: "production"
            test-suite: "some"
            version: "1.0.0"

  - label: ":github: Trigger E2E Tests (wait)"
    plugins:
      - elastic/vault-github-token#v0.1.0:
      - elastic/gh-cli#${BUILDKITE_COMMIT}:
          version: "2.62.0"
          workflow-file: "e2e-test.yml"
          workflow-ref: "main"
          workflow-inputs:
            enable-debug: "true"
            environment: "staging"
            test-suite: "all"
            version: "1.0.0"
          wait: true

  - label: ":github: Use GitHub CLI"
    plugins:
      - elastic/vault-github-token#v0.1.0:
      - elastic/gh-cli#${BUILDKITE_COMMIT}:
          version: "2.62.0"
    command: |
      gh --version
      gh repo view

  - label: ":test_tube: Run Plugin Unit Tests"
    commands:
      - make test
    agents:
      provider: gcp

  - label: ":mag: Run ShellCheck"
    commands:
      - make shellcheck
    agents:
      provider: gcp

  - label: ":lint-roller: Run Plugin Linter"
    commands:
      - make plugin-lint
    agents:
      provider: gcp
